crawler_app: support utf-8 for logging in file
This is because of the following error

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 85-90: character maps to <undefined>
Call stack:
  File "C:\Users\Stavros\workspace\GreekNewsScraper\Crawler.git\crawler_app.py", line 137, in <module>
    main()
  File "C:\Users\Stavros\workspace\GreekNewsScraper\Crawler.git\crawler_app.py", line 134, in main
    crawl_site(args.url, args.respect_robots, args.no_duplicates, args.crawl_delay, args.resume)
  File "C:\Users\Stavros\workspace\GreekNewsScraper\Crawler.git\crawler_app.py", line 97, in crawl_site
    save_link_to_db(database_name, domain, link, robots_parser)
  File "C:\Users\Stavros\workspace\GreekNewsScraper\Crawler.git\database.py", line 70, in save_link_to_db
    logging.info(f"Saved link to database: {link} (status: {status})")
Message: 'Saved link to database: https://www.tanea.gr/editor/δελλής-διονύσης/ (status: pending)'
Arguments: ()
```